#!/usr/bin/env bash
#Install nginx web server and set default page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx start
