#!/usr/bin/env bash
#Install nginx web server and set default page

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
