#!/usr/bin/env bash

# Install and configure HAproxy on your lb-01 server.


apt-get -y update
apt-get -y install haproxy=1.6.\*

echo 'frontend all-as.tech
        bind 0:80
        default_backend web_servers

    backend web_servers
            balance roundrobin
            server 529619-web-01 100.26.250.129:80
            server 529619-web-02 34.207.222.23:80
    ' >> /etc/haproxy/haproxy.cfg

service haproxy restart
