#!/usr/bin/env bash
# Configures an Ubuntu server 

sudo cp /etc/hosts ~/hosts.new
sudo echo "127.0.0.2		localhost" > ~/hosts.new
sudo echo "8.8.8.8		facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
