#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

service nginx stop

chown nginx:nginx /etc/nginx/nginx.conf

chmod 644 /etc/nginx/nginx.conf

sed -i 's/80/8080/g' /etc/nginx/sites-available/default

sudo -u nginx service nginx start

sudo -u nginx nginx
if pgrep -u nginx nginx > /dev/null
then
    echo "Nginx is running as nginx user"
else
    echo "Nginx is not running as nginx user"
fi
