#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

service nginx stop

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx

sed -i 's/^\(user\s*\)nginx;/\1nginx;\n\ndaemon off;\n\nmaster_process off;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 0.0.0.0:8080;/' /etc/nginx/sites-available/default

sudo -u nginx nginx
ps auxff | grep nginx
