#!/usr/bin/env bash
# Configure nginx to run as nginx user and listen on port 8080

pkill nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
